"""NotebookLM content extraction script.

Usage:
    python extract_notebooklm.py <notebook_url_or_id> <output_dir>

Extracts:
  - raw_text.md: Combined fulltext from all sources (up to 10)
  - notebooklm_report.md: Study Guide generated by NotebookLM
  - source_metadata.json: Notebook title, source count, source URLs
"""

import sys
import os
import json
import asyncio
import re

# Ensure stdout handles Unicode on Windows
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

MAX_SOURCES = 10


def parse_notebook_id(url_or_id: str) -> str:
    """Extract notebook ID from URL or return as-is if already an ID."""
    match = re.search(r'notebooklm\.google\.com/notebook/([a-zA-Z0-9_-]+)', url_or_id)
    if match:
        return match.group(1)
    return url_or_id.strip()


async def extract_notebooklm(url_or_id: str, output_dir: str):
    """Main extraction function for NotebookLM notebooks."""
    try:
        from notebooklm import NotebookLMClient
    except ImportError:
        print("ERROR: notebooklm-py is not installed. Run: pip install notebooklm-py")
        sys.exit(1)

    notebook_id = parse_notebook_id(url_or_id)
    if not notebook_id:
        print(f"ERROR: Could not parse notebook ID from: {url_or_id}")
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    try:
        async with await NotebookLMClient.from_storage() as client:
            await _extract(client, notebook_id, url_or_id, output_dir)
    except Exception as e:
        error_msg = str(e).lower()
        if any(w in error_msg for w in ('auth', 'credential', 'login', 'token', 'unauthorized')):
            print("ERROR: Not authenticated. Run: notebooklm login")
            sys.exit(1)
        print(f"ERROR: {e}")
        sys.exit(1)


async def _extract(client, notebook_id: str, original_url: str, output_dir: str):
    """Core extraction logic."""

    # 1. Get notebook info
    print(f"Connecting to notebook: {notebook_id}...")
    try:
        notebook = await client.notebooks.get(notebook_id)
    except Exception as e:
        print(f"ERROR: Could not access notebook '{notebook_id}': {e}")
        sys.exit(1)

    notebook_title = getattr(notebook, 'title', notebook_id)
    print(f"Notebook: {notebook_title}")

    # 2. List sources
    print("Fetching sources...")
    sources = await client.sources.list(notebook_id)
    source_count = len(sources)
    print(f"Found {source_count} source(s)")

    if source_count > MAX_SOURCES:
        print(f"WARNING: Notebook has {source_count} sources. Processing first {MAX_SOURCES} only.")
        sources = sources[:MAX_SOURCES]

    # 3. Part A: Get fulltext for each source
    print("Extracting source fulltexts...")
    source_info = []
    text_parts = []

    for i, source in enumerate(sources, 1):
        source_title = getattr(source, 'title', f'Source {i}')
        source_url = (
            getattr(source, 'url', None)
            or getattr(source, 'source_url', None)
            or ''
        )
        source_id = getattr(source, 'id', None) or getattr(source, 'source_id', None)
        print(f"  [{i}/{len(sources)}] {source_title}")

        source_info.append({
            "title": source_title,
            "url": source_url,
            "index": i,
        })

        try:
            fulltext = await client.sources.get_fulltext(notebook_id, source_id)
            if fulltext:
                header = f"## Source {i}: {source_title}"
                if source_url:
                    header += f"\n> {source_url}"
                text_parts.append(f"{header}\n\n{fulltext}")
        except Exception as e:
            print(f"    WARNING: Could not get fulltext for source {i}: {e}")
            continue

    if not text_parts:
        print("ERROR: Could not extract text from any sources.")
        sys.exit(1)

    # Combine all source texts with TOC if multiple
    if len(text_parts) > 1:
        toc_lines = ["# Sources\n"]
        for info in source_info:
            toc_lines.append(f"{info['index']}. {info['title']}")
        toc = "\n".join(toc_lines) + "\n\n---\n\n"
        raw_text = toc + "\n\n---\n\n".join(text_parts)
    else:
        raw_text = text_parts[0]

    raw_text_path = os.path.join(output_dir, "raw_text.md")
    with open(raw_text_path, "w", encoding="utf-8") as f:
        f.write(raw_text)
    print(f"SUCCESS (A): raw_text.md — {len(raw_text)} chars from {len(text_parts)} source(s)")

    # 4. Part B: Generate Study Guide
    print("Generating Study Guide (this may take 1-2 minutes)...")
    report_path = os.path.join(output_dir, "notebooklm_report.md")
    try:
        status = await client.artifacts.generate_study_guide(notebook_id, language="ko")
        await client.artifacts.wait_for_completion(notebook_id, status.task_id)
        await client.artifacts.download_report(notebook_id, report_path)
        print(f"SUCCESS (B): notebooklm_report.md written")
    except Exception as e:
        print(f"WARNING: Could not generate/download Study Guide: {e}")
        print("  Proceeding without notebooklm_report.md - content-analyzer will use raw_text.md only")

    # 5. Write source_metadata.json
    if 'notebooklm.google.com' in original_url:
        notebook_url = original_url
    else:
        notebook_url = f"https://notebooklm.google.com/notebook/{notebook_id}"

    metadata = {
        "notebook_id": notebook_id,
        "notebook_title": notebook_title,
        "notebook_url": notebook_url,
        "source_count": source_count,
        "sources_processed": len(text_parts),
        "sources": source_info,
    }
    metadata_path = os.path.join(output_dir, "source_metadata.json")
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)

    print(f"  → {raw_text_path}")
    if os.path.exists(report_path):
        print(f"  → {report_path}")
    print(f"  → {metadata_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python extract_notebooklm.py <notebook_url_or_id> <output_dir>")
        sys.exit(1)

    url_or_id = sys.argv[1]
    output_dir = sys.argv[2]
    asyncio.run(extract_notebooklm(url_or_id, output_dir))
